# Generated by Django 6.0.3 on 2026-03-04 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_helpticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeNoteReport',
            fields=[
            ],
            options={
                'verbose_name': 'Fake Note Report',
                'verbose_name_plural': 'Fake Note Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.helpticket',),
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=10)),
                ('confidence', models.CharField(max_length=20)),
                ('source_file', models.CharField(blank=True, max_length=120)),
                ('pdf_file', models.FileField(upload_to='reports/generated/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
